name: Build SDL Core

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at 5 AM UTC


jobs:
  build-windows:
    name: Download Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          arch: [x64, x86, arm64]

    steps:
      - name: Download release build
        run: wget https://github.com/libsdl-org/SDL/releases/download/release-${{ env.SDL3_VERSION }}/SDL3-${{ env.SDL3_VERSION }}-win32-${{ matrix.arch }}.zip
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-windows-${{ matrix.arch }}
            path: SDL3-${{ env.SDL3_VERSION }}-win32-${{ matrix.arch }}.zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
    defaults:
      run:
        working-directory: SDL
    steps:
      - name: Clone SDL3
        working-directory: .
        run: git clone --depth 1 --branch release-${{ env.SDL3_VERSION }} https://github.com/libsdl-org/SDL.git
      - name: Configure
        run: >
          cmake -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-linux
            path: SDL/build/*.so.0

  build-macos:
    name: Build for Apple
    runs-on: macos-14
    defaults:
      run:
        working-directory: SDL
    strategy:
      fail-fast: false
      matrix:
          target: [iOS, '']
    steps:
      - name: Clone SDL3
        working-directory: .
        run: git clone --depth 1 --branch release-${{ env.SDL3_VERSION }} https://github.com/libsdl-org/SDL.git
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
            xcode-version: "16.1"
      - name: Configure
        run: >
          cmake -G "Xcode"
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
          -DCMAKE_SYSTEM_NAME=${{ matrix.target }}
          -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-apple-${{ matrix.target }}
            path: SDL/build/*
