name: Build SDL Core

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at 5 AM UTC


jobs:
  determine-version:
    name: Determine Latest SDL3 Version
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.get_version.outputs.release_tag }}
      version_number: ${{ steps.get_version.outputs.version_number }}
    steps:
      - name: Get latest SDL3 release info
        id: get_version
        run: |
          RELEASE_TAG=$(gh release list --repo libsdl-org/SDL --limit 1 --json tagName | jq -r ".[0].tagName")
          echo "Determined RELEASE_TAG: ${RELEASE_TAG}"
          # Ensure RELEASE_TAG is not empty or null
          if [ -z "${RELEASE_TAG}" ] || [ "${RELEASE_TAG}" == "null" ]; then
            echo "::error::Failed to determine RELEASE_TAG."
            exit 1
          fi
          echo "release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
          VERSION_NUMBER=$(echo "${RELEASE_TAG}" | sed 's/^release-//')
          echo "Determined VERSION_NUMBER: ${VERSION_NUMBER}"
          if [ -z "${VERSION_NUMBER}" ]; then
            echo "::error::Failed to determine VERSION_NUMBER from RELEASE_TAG: ${RELEASE_TAG}."
            exit 1
          fi
          echo "version_number=${VERSION_NUMBER}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Download Windows
    runs-on: ubuntu-latest
    needs: determine-version
    strategy:
      fail-fast: false
      matrix:
          arch: [x64]

    steps:
      - name: Download release build
        run: wget https://github.com/libsdl-org/SDL/releases/download/${{ needs.determine-version.outputs.release_tag }}/SDL3-${{ needs.determine-version.outputs.version_number }}-win32-x64.zip
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-windows-x64
            path: SDL3-${{ needs.determine-version.outputs.version_number }}-win32-x64.zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: determine-version
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
    defaults:
      run:
        working-directory: SDL
    steps:
      - name: Clone SDL3
        working-directory: .
        run: git clone --depth 1 --branch ${{ needs.determine-version.outputs.release_tag }} https://github.com/libsdl-org/SDL.git
      - name: Configure
        run: >
          cmake -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Package Linux library
        working-directory: SDL/build
        run: |
          # Assuming libSDL3.so.0 is the correct file, based on previous logs
          zip "../SDL3-${{ needs.determine-version.outputs.version_number }}-linux-x86_64.zip" libSDL3.so.0
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
            name: sdl-linux-zip
            path: SDL/SDL3-${{ needs.determine-version.outputs.version_number }}-linux-x86_64.zip

  build-macos:
    name: Build for Apple
    runs-on: macos-14
    needs: determine-version
    defaults:
      run:
        working-directory: SDL
    steps:
      - name: Clone SDL3
        working-directory: .
        run: git clone --depth 1 --branch ${{ needs.determine-version.outputs.release_tag }} https://github.com/libsdl-org/SDL.git
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
            xcode-version: "16.1"
      - name: Configure
        run: >
          cmake -G "Xcode"
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
          -DCMAKE_SYSTEM_NAME=${{ matrix.target }}
          -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Package macOS library
        working-directory: SDL/build/Release
        run: |
          # Zipping libSDL3.0.dylib, which is typically the actual library file
          zip "../../SDL3-${{ needs.determine-version.outputs.version_number }}-macos-${{ matrix.arch }}.zip" libSDL3.0.dylib
      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
            name: sdl-apple-${{ matrix.arch }}-zip
            path: SDL/SDL3-${{ needs.determine-version.outputs.version_number }}-macos-${{ matrix.arch }}.zip

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [determine-version, build-windows, build-linux, build-macos]
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts # All artifacts will be downloaded into subdirectories under 'artifacts'

      - name: List downloaded files (for debugging)
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.determine-version.outputs.release_tag }}
          name: "SDL Core ${{ needs.determine-version.outputs.version_number }}"
          body: "Automated release for SDL Core version ${{ needs.determine-version.outputs.version_number }}, including builds for Windows, Linux, and Apple platforms."
          files: |
            artifacts/sdl-windows-x64/SDL3-${{ needs.determine-version.outputs.version_number }}-win32-x64.zip
            artifacts/sdl-linux-zip/*.zip
            artifacts/sdl-apple-arm64-zip/*.zip
            artifacts/sdl-apple-x86_64-zip/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
